#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-merge'.\n"; exit 2; }
git lfs post-merge "$@"

function determineBuildStatus() {
    input="$1"

    if [ ! "$input" ];then
        build_status="None"
    else
        build_status="Build"
    fi
}

function findScriptsLocation() {
    scripts_path=$(find . -name "UploadLogs.bat")
    scripts_path=$(dirname $scripts_path)
}

function updateBuildStatus() {
	echo "New build status: $1"
    findScriptsLocation
    echo $1 > $scripts_path/BuildStatus.txt
}

determineBuildStatus "$(git log --name-status ORIG_HEAD..HEAD | grep Source/)"
updateBuildStatus "$build_status"