#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"; exit 2; }
git lfs post-checkout "$@"

function determineBuildStatus() {
    input="$1"

    if [ ! "$input" ];then
        build_status="None"
    else
        build_status="Build"
    fi
}

function findScriptsLocation() {
    scripts_path=$(find . -name "UploadLogs.bat")
    scripts_path=$(dirname $scripts_path)
}

function updateBuildStatus() {
	echo "New build status: $1"
    findScriptsLocation
    echo $1 > $scripts_path/BuildStatus.txt
}

# Check if branch was switched
if [ "$3" == "1" ]; then
    last_branch_name=$(git name-rev $(git rev-parse @{-1}) --name-only)
    current_branch_name=$(git rev-parse --abbrev-ref HEAD)
    determineBuildStatus "$(git diff --name-status $last_branch_name $current_branch_name | grep Source/)"
    updateBuildStatus "$build_status"
    exit 0
fi

determineBuildStatus "$(git log --name-status ORIG_HEAD..HEAD | grep Source/)"
updateBuildStatus "$build_status"